pinterest/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', AccountDeleteView.as_view(), name='delete'),
]

pinterest/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView,ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pinterest/pinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinterest/projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

pinterest/subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

pinterest/templates/base.html
<!DOCTYPE html>
<html lang="kr">

{% include 'head.html' %}

<body style="font-family: NanumSquareOTFRegular">

    {% include 'header.html' %}
    <hr>
    {% block content %}
    {% endblock %}
    <hr>
    {% include 'footer.html' %}

</body>
</html>

pinterest/templates/footer.html
<div class="footer_container">
    <div class="footer_button">
        <span>공지사항</span> |
        <span>제휴 문의</span> |
        <span>서비스 소개</span>
    </div>
    <div class="footer_logo">
        <h6 >JoeJaeSo</h6>
    </div>
</div>

pinterest/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pinterest</title>
    <!--    BOOTSTRAP LINK-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!--    FONT Pacifico-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <!--    DEFAULT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <!--    GOOLE MATERIAL ICONS-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <style>
        @font-face {
            font-family: 'NanumSquareOTFBOLD';
            src: local('NanumSquareOTFBOLD'),
            url("{% static 'fonts/NanumSquareOTFBOLD.ttf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareOTFExtraBold';
            src: local('NanumSquareOTFExtraBold'),
            url("{% static 'fonts/NanumSquareOTFExtraBold.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareOTFLight';
            src: local('NanumSquareOTFLight'),
            url("{% static 'fonts/NanumSquareOTFLight.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareOTFRegular';
            src: local('NanumSquareOTFRegular'),
            url("{% static 'fonts/NanumSquareOTFRegular.otf' %}") format("opentype");
        }
    </style>
</head>

pinterest/templates/header.html
<div class="header_container">
    <div>
        <h1 class="header_logo">Pinterest</h1>
    </div>
    <div class="header_navbar">
       <a href="{% url 'articleapp:list' %}" class="header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="header_nav">
            <span>Projects</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="header_nav">
            <span>Subscription</span>
        </a>

        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="header_nav">
            <span>Login</span>

        </a>
        <a href="{% url 'accountapp:create' %}" class="header_nav">
            <span>Sign Up</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="header_nav">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="header_nav">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>